### ISSUE TITLE
If parent entities are not in synced state, does worker manager waits 15 minutes to try to sync them again?

### ISSUE THREAD

**Issue by mateoKutnjak** [Ikhiloya/WorkManager-Dependent-Periodic-Task#1]
Lets say I have entities A, B and C. A is independent class (it does not have any foreign key dependencies). B depends on A and C depends on B 

C -> B -> A

If it happens that there are three entities (A, B and C) and neither of them is in synced state. How long does it takes with your WorkManager architecture to sync all three entities to remote database? 

WorkManager is triggered minimally every 15 minutes. Does that mean when entity C is being synced and it has non-synced parent entity B it waits 15 minutes to sync entity B which sees that entity A is not synced and it still waits 15 minutes to sync entity A?

**Comment by Ikhiloya** [comment]
Yes, it’ll take as much time to sync. That means C will not sync to the remote until B is synced and, B 
will not sync until A is synced. This is triggered minimally every 15minutes according to the workmanager architecture.

More so, you don’t want to have “orphaned” data in your remote database.

Also note that all workmanagers(for A, B, C are triggered at different times, 15 minutes apart for each unique call).
When C is called and B is not synced, it waits till the next 15 minutes to try to sync again, it only becomes successful when B is synced.
