### ISSUE TITLE
How to sync local deletion of data?

### ISSUE THREAD

**Issue by mateoKutnjak** [Ikhiloya/WorkManager-Dependent-Periodic-Task#2]
Let's say we have local entries that we delete. How to sync removal of this local data to remote server?

**Comment by Ikhiloya** [comment]
You can delete pretty much  the same way you save. If you delete the parent, you have to delete all its dependents. However, you can delete a child without deleting the parent. It all depends on your use case. Be careful of having orphaned data. 
Think of "delete cascade".
